version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Ou a versão que você estiver usando
  build:
    commands:
      - dotnet restore
      - dotnet build --configuration Release
  post_build:
    commands:
      - dotnet publish -c Release -o ./publish
artifacts:
  files:
    - '**/*'
  base-directory: ./publish
