version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build --configuration Release
      - dotnet test --configuration Release
  post_build:
    commands:
      - dotnet publish --configuration Release --output ./publish

artifacts:
  files:
    - ./publish/**/*
  discard-paths: yes
